# Use an appropriate JDK base image
FROM openjdk:17-alpine

# Set working directory inside the container
WORKDIR /app

# Expose the application port
EXPOSE 9090

# Copy the JAR file generated by the build process into the container
COPY target/*.jar /app/gabriel_tour_app_backend-1.0-SNAPSHOT.jar

# Set the entrypoint to run the application using the JAR file
ENTRYPOINT ["java", "-jar", "/app/gabriel_tour_app_backend-1.0-SNAPSHOT.jar"]
