name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      # Step 3: Build the project with Maven
      - name: Build Project with Maven
        run: mvn clean install

      # Step 4: Log in to AWS ECR
      - name: Log in to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        env:
          AWS_REGION: eu-north-1 # Replace with your desired region
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 5: Build the Docker image
      - name: Build Docker Image
        run: docker build -t gabrieltour:latest .

      # Step 6: Tag the Docker image
      - name: Tag Docker Image
        run: docker tag gabrieltour:latest 967777613408.dkr.ecr.eu-north-1.amazonaws.com/gabrieltour:latest

      # Step 7: Push Docker image to AWS ECR
      - name: Push Docker Image to AWS ECR
        run: docker push 967777613408.dkr.ecr.eu-north-1.amazonaws.com/gabrieltour:latest
