name: Push
on:
  push:
    branches:
      - "*"
      - "!main"
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit