name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - dev  # Trigger the workflow on push to the branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3

      # Install dependencies and run tests
      - name: Install dependencies and run tests
        run: |
          mvn clean install
          mvn test