name: test

on:
  push:
    branches:
      - dev  # Trigger the workflow on push to the branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # Install dependencies and run tests
      - name: Install dependencies and run tests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://database-1.c3acismuom6n.eu-north-1.rds.amazonaws.com:5432/postgres
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: IG16072002
        run: |
          mvn clean install
          mvn test